/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.window;

import static com.android.internal.annotations.VisibleForTesting.Visibility.PROTECTED;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.content.ComponentName;
import android.os.Parcelable;

import com.android.internal.annotations.VisibleForTesting;
import com.android.internal.util.DataClass;

/**
 * Holds information specific to an activity during a transition.
 *
 * <p>This class is used within {@link TransitionInfo.Change} to encapsulate
 * details relevant only when the transitioning container is an activity.
 *
 * @hide
 */
@DataClass(genConstructor = true, genGetters = true, genEqualsHashCode = true,
        genParcelable = true, genToString = true)
public final class ActivityTransitionInfo implements Parcelable {
    @NonNull
    private final ComponentName mComponent;
    private final int mTaskId;
    @Nullable
    private final AppCompatTransitionInfo mAppCompatTransitionInfo;

    @VisibleForTesting(visibility = PROTECTED)
    public ActivityTransitionInfo(@NonNull ActivityTransitionInfo other) {
        this(other.mComponent.clone(), other.mTaskId, other.mAppCompatTransitionInfo);
    }

    public ActivityTransitionInfo(@NonNull ComponentName component, int taskId) {
        this(component, taskId, null);
    }

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/window/ActivityTransitionInfo.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public ActivityTransitionInfo(
            @NonNull ComponentName component,
            int taskId,
            @Nullable AppCompatTransitionInfo appCompatTransitionInfo) {
        this.mComponent = component;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mComponent);
        this.mTaskId = taskId;
        this.mAppCompatTransitionInfo = appCompatTransitionInfo;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public @NonNull ComponentName getComponent() {
        return mComponent;
    }

    @DataClass.Generated.Member
    public int getTaskId() {
        return mTaskId;
    }

    @DataClass.Generated.Member
    public @Nullable AppCompatTransitionInfo getAppCompatTransitionInfo() {
        return mAppCompatTransitionInfo;
    }

    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "ActivityTransitionInfo { " +
                "component = " + mComponent + ", " +
                "taskId = " + mTaskId + ", " +
                "appCompatTransitionInfo = " + mAppCompatTransitionInfo +
        " }";
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(ActivityTransitionInfo other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        ActivityTransitionInfo that = (ActivityTransitionInfo) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mComponent, that.mComponent)
                && mTaskId == that.mTaskId
                && java.util.Objects.equals(mAppCompatTransitionInfo, that.mAppCompatTransitionInfo);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mComponent);
        _hash = 31 * _hash + mTaskId;
        _hash = 31 * _hash + java.util.Objects.hashCode(mAppCompatTransitionInfo);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mAppCompatTransitionInfo != null) flg |= 0x4;
        dest.writeByte(flg);
        dest.writeTypedObject(mComponent, flags);
        dest.writeInt(mTaskId);
        if (mAppCompatTransitionInfo != null) dest.writeTypedObject(mAppCompatTransitionInfo, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ ActivityTransitionInfo(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        ComponentName component = (ComponentName) in.readTypedObject(ComponentName.CREATOR);
        int taskId = in.readInt();
        AppCompatTransitionInfo appCompatTransitionInfo = (flg & 0x4) == 0 ? null : (AppCompatTransitionInfo) in.readTypedObject(AppCompatTransitionInfo.CREATOR);

        this.mComponent = component;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mComponent);
        this.mTaskId = taskId;
        this.mAppCompatTransitionInfo = appCompatTransitionInfo;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<ActivityTransitionInfo> CREATOR
            = new Parcelable.Creator<ActivityTransitionInfo>() {
        @Override
        public ActivityTransitionInfo[] newArray(int size) {
            return new ActivityTransitionInfo[size];
        }

        @Override
        public ActivityTransitionInfo createFromParcel(@NonNull android.os.Parcel in) {
            return new ActivityTransitionInfo(in);
        }
    };

    @DataClass.Generated(
            time = 1748332897391L,
            codegenVersion = "1.0.23",
            sourceFile = "frameworks/base/core/java/android/window/ActivityTransitionInfo.java",
            inputSignatures = "private final @android.annotation.NonNull android.content.ComponentName mComponent\nprivate final  int mTaskId\nprivate final @android.annotation.Nullable android.window.AppCompatTransitionInfo mAppCompatTransitionInfo\nclass ActivityTransitionInfo extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=true, genGetters=true, genEqualsHashCode=true, genParcelable=true, genToString=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
