/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.window;

import android.annotation.NonNull;
import android.graphics.Rect;
import android.os.Parcelable;

import com.android.internal.util.DataClass;

/**
 * Encapsulate all the information useful to AppCompat in an Activity transition.
 *
 * @hide
 */
@DataClass(genConstructor = true, genGetters = true, genEqualsHashCode = true,
        genParcelable = true, genToString = true)
public class AppCompatTransitionInfo implements Parcelable {

    @NonNull
    private final Rect mLetterboxBounds;

    private final boolean mHasRoundedCorners;

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/window/AppCompatTransitionInfo.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public AppCompatTransitionInfo(
            @NonNull Rect letterboxBounds,
            boolean hasRoundedCorners) {
        this.mLetterboxBounds = letterboxBounds;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mLetterboxBounds);
        this.mHasRoundedCorners = hasRoundedCorners;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public @NonNull Rect getLetterboxBounds() {
        return mLetterboxBounds;
    }

    @DataClass.Generated.Member
    public boolean isHasRoundedCorners() {
        return mHasRoundedCorners;
    }

    @Override
    @DataClass.Generated.Member
    public String toString() {
        // You can override field toString logic by defining methods like:
        // String fieldNameToString() { ... }

        return "AppCompatTransitionInfo { " +
                "letterboxBounds = " + mLetterboxBounds + ", " +
                "hasRoundedCorners = " + mHasRoundedCorners +
        " }";
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(AppCompatTransitionInfo other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        AppCompatTransitionInfo that = (AppCompatTransitionInfo) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mLetterboxBounds, that.mLetterboxBounds)
                && mHasRoundedCorners == that.mHasRoundedCorners;
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mLetterboxBounds);
        _hash = 31 * _hash + Boolean.hashCode(mHasRoundedCorners);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mHasRoundedCorners) flg |= 0x2;
        dest.writeByte(flg);
        dest.writeTypedObject(mLetterboxBounds, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected AppCompatTransitionInfo(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        boolean hasRoundedCorners = (flg & 0x2) != 0;
        Rect letterboxBounds = (Rect) in.readTypedObject(Rect.CREATOR);

        this.mLetterboxBounds = letterboxBounds;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mLetterboxBounds);
        this.mHasRoundedCorners = hasRoundedCorners;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<AppCompatTransitionInfo> CREATOR
            = new Parcelable.Creator<AppCompatTransitionInfo>() {
        @Override
        public AppCompatTransitionInfo[] newArray(int size) {
            return new AppCompatTransitionInfo[size];
        }

        @Override
        public AppCompatTransitionInfo createFromParcel(@NonNull android.os.Parcel in) {
            return new AppCompatTransitionInfo(in);
        }
    };

    @DataClass.Generated(
            time = 1752247427001L,
            codegenVersion = "1.0.23",
            sourceFile = "frameworks/base/core/java/android/window/AppCompatTransitionInfo.java",
            inputSignatures = "private final @android.annotation.NonNull android.graphics.Rect mLetterboxBounds\nprivate final  boolean mHasRoundedCorners\nclass AppCompatTransitionInfo extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=true, genGetters=true, genEqualsHashCode=true, genParcelable=true, genToString=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
