/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.app.ondeviceintelligence.imagedescription;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;
import android.annotation.SystemApi;
import android.app.ondeviceintelligence.OnDeviceIntelligenceException;
import android.app.ondeviceintelligence.flags.Flags;

/**
 * Callback for receiving generated image descriptions.
 *
 * <p>This callback allows for both streaming of partial results and receiving the final,
 * cumulative description.
 *
 * @hide
 */
@SystemApi
@FlaggedApi(Flags.FLAG_ON_DEVICE_INTELLIGENCE_26Q2)
public interface ImageDescriptionCallback {
    /**
     * Called periodically to stream the output chunks of the image description.
     *
     * @param text The partial description text generated by the model.
     */
    void onNewText(@NonNull String text);

    /**
     * Called when the image description generation is complete.
     *
     * <p>After the streaming is complete, this method will be invoked with the cumulative output.
     * If the total output is too large to send via binder, the {@link ImageDescriptionResponse}
     * may be populated with an empty description to indicate that the streaming is complete,
     * as the content has already been streamed via {@link #onNewText(String)}.
     *
     * @param result The final generated description response.
     */
    void onResult(@NonNull ImageDescriptionResponse result);

    /**
     * Called when an error occurs during the image description generation.
     *
     * @param error An exception describing the error that occurred.
     */
    void onError(@NonNull OnDeviceIntelligenceException error);
}
