/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package android.health.connect.datatypes;

import static android.health.connect.datatypes.RecordTypeIdentifier.RECORD_TYPE_POWER;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.health.connect.HealthConnectManager;
import android.health.connect.datatypes.units.Power;
import android.health.connect.datatypes.validation.ValidationUtils;
import android.health.connect.internal.datatypes.PowerRecordInternal;

import com.android.healthfitness.flags.Flags;

import java.time.Instant;
import java.time.ZoneOffset;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;

/** Captures the power generated by the user, e.g. during cycling or rowing with a power meter. */
@Identifier(recordIdentifier = RECORD_TYPE_POWER)
public final class PowerRecord extends IntervalRecord {
    private final List<PowerRecordSample> mSamples;

    /**
     * @param metadata Metadata to be associated with the record. See {@link Metadata}.
     * @param startTime Start time of this activity
     * @param startZoneOffset Zone offset of the user when the activity started
     * @param endTime End time of this activity
     * @param endZoneOffset Zone offset of the user when the activity finished
     * @param samples Samples of recorded PowerRecord, sorted by time.
     * @param skipValidation Boolean flag to skip validation of record values.
     */
    private PowerRecord(
            @NonNull Metadata metadata,
            @NonNull Instant startTime,
            @NonNull ZoneOffset startZoneOffset,
            @NonNull Instant endTime,
            @NonNull ZoneOffset endZoneOffset,
            @NonNull List<PowerRecordSample> samples,
            boolean skipValidation) {
        super(
                metadata,
                startTime,
                startZoneOffset,
                endTime,
                endZoneOffset,
                skipValidation,
                /* enforceFutureTimeRestrictions= */ true);
        Objects.requireNonNull(samples);
        if (!skipValidation) {
            ValidationUtils.validateSampleStartAndEndTime(
                    startTime,
                    endTime,
                    samples.stream().map(PowerRecord.PowerRecordSample::getTime).toList());
        }
        mSamples = samples;
    }

    /**
     * @return PowerRecord samples corresponding to this record, in ascending time order
     */
    @NonNull
    public List<PowerRecordSample> getSamples() {
        return mSamples;
    }

    /**
     * Represents a single measurement of power. For example, using a power meter when exercising on
     * a stationary bike.
     */
    public static final class PowerRecordSample {
        private final Power mPower;
        private final Instant mTime;

        /**
         * PowerRecord sample for entries of {@link PowerRecord}
         *
         * @param power Power generated, in {@link Power} unit.
         * @param time The point in time when the measurement was taken.
         */
        public PowerRecordSample(@NonNull Power power, @NonNull Instant time) {
            this(power, time, false);
        }

        /**
         * PowerRecord sample for entries of {@link PowerRecord}
         *
         * @param power Power generated, in {@link Power} unit.
         * @param time The point in time when the measurement was taken.
         * @param skipValidation Boolean flag to skip validation of record values.
         * @hide
         */
        public PowerRecordSample(
                @NonNull Power power, @NonNull Instant time, boolean skipValidation) {
            Objects.requireNonNull(time);
            Objects.requireNonNull(power);
            if (!skipValidation) {
                ValidationUtils.requireInRange(power.getInWatts(), 0.0, 100000.0, "power");
            }
            mTime = time;
            mPower = power;
        }

        /**
         * @return Power for this sample
         */
        @NonNull
        public Power getPower() {
            return mPower;
        }

        /**
         * @return time at which this sample was recorded
         */
        @NonNull
        public Instant getTime() {
            return mTime;
        }

        /**
         * Indicates whether some other object is "equal to" this one.
         *
         * @param object the reference object with which to compare.
         * @return {@code true} if this object is the same as the obj
         */
        @Override
        public boolean equals(Object object) {
            if (this == object) return true;
            if (!(object instanceof PowerRecordSample that)) return false;
            return Objects.equals(mPower, that.mPower)
                    && (mTime.toEpochMilli() == that.mTime.toEpochMilli());
        }

        /**
         * Returns a hash code value for the object.
         *
         * @return a hash code value for this object.
         */
        @Override
        public int hashCode() {
            return Objects.hash(getPower(), getTime());
        }
    }

    /** Builder class for {@link PowerRecord} */
    public static final class Builder {
        private final Metadata mMetadata;
        private final Instant mStartTime;
        private final Instant mEndTime;
        private final List<PowerRecordSample> mSamples;
        private ZoneOffset mStartZoneOffset;
        private ZoneOffset mEndZoneOffset;

        /**
         * @param metadata Metadata to be associated with the record. See {@link Metadata}.
         * @param startTime Start time of this activity
         * @param endTime End time of this activity
         * @param powerRecordSamples Samples of recorded PowerRecord. Only a single sample with a
         *     given time is accepted and samples with duplicate times will be silently dropped.
         */
        public Builder(
                @NonNull Metadata metadata,
                @NonNull Instant startTime,
                @NonNull Instant endTime,
                @NonNull List<PowerRecordSample> powerRecordSamples) {
            Objects.requireNonNull(metadata);
            Objects.requireNonNull(startTime);
            Objects.requireNonNull(endTime);
            Objects.requireNonNull(powerRecordSamples);
            mMetadata = metadata;
            mStartTime = startTime;
            mEndTime = endTime;
            if (Flags.sampleTimeOrdering()) {
                TreeSet<PowerRecordSample> sampleSet =
                        new TreeSet<>(Comparator.comparing(PowerRecordSample::getTime));
                sampleSet.addAll(powerRecordSamples);
                mSamples = sampleSet.stream().toList();
            } else {
                mSamples = powerRecordSamples;
            }
            mStartZoneOffset = ZoneOffset.systemDefault().getRules().getOffset(startTime);
            mEndZoneOffset = ZoneOffset.systemDefault().getRules().getOffset(endTime);
        }

        /** Sets the zone offset of the user when the activity started */
        @NonNull
        public Builder setStartZoneOffset(@NonNull ZoneOffset startZoneOffset) {
            Objects.requireNonNull(startZoneOffset);
            mStartZoneOffset = startZoneOffset;
            return this;
        }

        /** Sets the zone offset of the user when the activity ended */
        @NonNull
        public Builder setEndZoneOffset(@NonNull ZoneOffset endZoneOffset) {
            Objects.requireNonNull(endZoneOffset);
            mEndZoneOffset = endZoneOffset;
            return this;
        }

        /** Sets the start zone offset of this record to system default. */
        @NonNull
        public Builder clearStartZoneOffset() {
            mStartZoneOffset = RecordUtils.getDefaultZoneOffset();
            return this;
        }

        /** Sets the start zone offset of this record to system default. */
        @NonNull
        public Builder clearEndZoneOffset() {
            mEndZoneOffset = RecordUtils.getDefaultZoneOffset();
            return this;
        }

        /**
         * @return Object of {@link PowerRecord} without validating the values.
         * @hide
         */
        @NonNull
        public PowerRecord buildWithoutValidation() {
            return new PowerRecord(
                    mMetadata,
                    mStartTime,
                    mStartZoneOffset,
                    mEndTime,
                    mEndZoneOffset,
                    mSamples,
                    true);
        }

        /**
         * @return Object of {@link PowerRecord}
         */
        @NonNull
        public PowerRecord build() {
            return new PowerRecord(
                    mMetadata,
                    mStartTime,
                    mStartZoneOffset,
                    mEndTime,
                    mEndZoneOffset,
                    mSamples,
                    false);
        }
    }

    /** Metric identifier to get max power using aggregate APIs in {@link HealthConnectManager} */
    @NonNull
    public static final AggregationType<Power> POWER_MAX =
            new AggregationType<>(
                    AggregationType.AggregationTypeIdentifier.POWER_RECORD_POWER_MAX,
                    AggregationType.MAX,
                    RECORD_TYPE_POWER,
                    Power.class);

    /** Metric identifier to get min power using aggregate APIs in {@link HealthConnectManager} */
    @NonNull
    public static final AggregationType<Power> POWER_MIN =
            new AggregationType<>(
                    AggregationType.AggregationTypeIdentifier.POWER_RECORD_POWER_MIN,
                    AggregationType.MIN,
                    RECORD_TYPE_POWER,
                    Power.class);

    /** Metric identifier to get avg power using aggregate APIs in {@link HealthConnectManager} */
    @NonNull
    public static final AggregationType<Power> POWER_AVG =
            new AggregationType<>(
                    AggregationType.AggregationTypeIdentifier.POWER_RECORD_POWER_AVG,
                    AggregationType.AVG,
                    RECORD_TYPE_POWER,
                    Power.class);

    /**
     * Indicates whether some other object is "equal to" this one.
     *
     * @param object the reference object with which to compare.
     * @return {@code true} if this object is the same as the obj
     */
    @Override
    public boolean equals(@Nullable Object object) {
        if (super.equals(object) && object instanceof PowerRecord other) {
            return Objects.equals(getSamples(), other.getSamples());
        }
        return false;
    }

    /** Returns a hash code value for the object. */
    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), getSamples());
    }

    /** @hide */
    @Override
    public PowerRecordInternal toRecordInternal() {
        Set<PowerRecordInternal.PowerRecordSample> samples = new HashSet<>(getSamples().size());
        for (PowerRecord.PowerRecordSample powerRecordSample : getSamples()) {
            samples.add(
                    new PowerRecordInternal.PowerRecordSample(
                            powerRecordSample.getPower().getInWatts(),
                            powerRecordSample.getTime().toEpochMilli()));
        }
        PowerRecordInternal recordInternal =
                (PowerRecordInternal) new PowerRecordInternal(samples).setMetaData(getMetadata());
        recordInternal.setTimeInterval(this);

        return recordInternal;
    }
}
