/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.internal.pm.pkg.component;

import android.annotation.NonNull;
import android.os.Parcelable;

import com.android.internal.util.DataClass;
import com.android.internal.util.Parcelling;

/**
 * A {@link android.R.styleable#AndroidManifestValidGeneralPurpose &lt;valid-general-purpose&gt;}
 * tag parsed from
 * the manifest.
 *
 * @hide
 */
@DataClass(genGetters = true, genSetters = true, genBuilder = false, genParcelable = true,
        genAidl = false)
public class ParsedValidGeneralPurposeImpl implements ParsedValidGeneralPurpose, Parcelable {
    @DataClass.ParcelWith(Parcelling.BuiltIn.ForInternedString.class)
    @NonNull
    private String mName;

    private int mMaxTargetSdkVersion;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/com/android/internal/pm/pkg/component/ParsedValidGeneralPurposeImpl.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    public ParsedValidGeneralPurposeImpl(
            @NonNull String name,
            int maxTargetSdkVersion) {
        this.mName = name;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mName);
        this.mMaxTargetSdkVersion = maxTargetSdkVersion;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public @NonNull String getName() {
        return mName;
    }

    @DataClass.Generated.Member
    public int getMaxTargetSdkVersion() {
        return mMaxTargetSdkVersion;
    }

    @DataClass.Generated.Member
    public @NonNull ParsedValidGeneralPurposeImpl setName(@NonNull String value) {
        mName = value;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mName);
        return this;
    }

    @DataClass.Generated.Member
    public @NonNull ParsedValidGeneralPurposeImpl setMaxTargetSdkVersion( int value) {
        mMaxTargetSdkVersion = value;
        return this;
    }

    @DataClass.Generated.Member
    static Parcelling<String> sParcellingForName =
            Parcelling.Cache.get(
                    Parcelling.BuiltIn.ForInternedString.class);
    static {
        if (sParcellingForName == null) {
            sParcellingForName = Parcelling.Cache.put(
                    new Parcelling.BuiltIn.ForInternedString());
        }
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        sParcellingForName.parcel(mName, dest, flags);
        dest.writeInt(mMaxTargetSdkVersion);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    protected ParsedValidGeneralPurposeImpl(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        String name = sParcellingForName.unparcel(in);
        int maxTargetSdkVersion = in.readInt();

        this.mName = name;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mName);
        this.mMaxTargetSdkVersion = maxTargetSdkVersion;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<ParsedValidGeneralPurposeImpl> CREATOR
            = new Parcelable.Creator<ParsedValidGeneralPurposeImpl>() {
        @Override
        public ParsedValidGeneralPurposeImpl[] newArray(int size) {
            return new ParsedValidGeneralPurposeImpl[size];
        }

        @Override
        public ParsedValidGeneralPurposeImpl createFromParcel(@NonNull android.os.Parcel in) {
            return new ParsedValidGeneralPurposeImpl(in);
        }
    };

    @DataClass.Generated(
            time = 1758768270258L,
            codegenVersion = "1.0.23",
            sourceFile = "frameworks/base/core/java/com/android/internal/pm/pkg/component/ParsedValidGeneralPurposeImpl.java",
            inputSignatures = "private @com.android.internal.util.DataClass.ParcelWith(com.android.internal.util.Parcelling.BuiltIn.ForInternedString.class) @android.annotation.NonNull java.lang.String mName\nprivate  int mMaxTargetSdkVersion\nclass ParsedValidGeneralPurposeImpl extends java.lang.Object implements [com.android.internal.pm.pkg.component.ParsedValidGeneralPurpose, android.os.Parcelable]\n@com.android.internal.util.DataClass(genGetters=true, genSetters=true, genBuilder=false, genParcelable=true, genAidl=false)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
