/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.os.vibrator;

import static java.util.Objects.requireNonNull;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;
import android.annotation.RequiresPermission;
import android.annotation.SystemApi;
import android.media.AudioFormat;
import android.os.Parcel;
import android.os.Parcelable;
import android.os.ParcelableHolder;
import android.os.RemoteException;
import android.os.VibrationEffect;
import android.util.Slog;

import androidx.annotation.Nullable;

import com.android.internal.util.Preconditions;

/**
 * Represents an active session for generating haptic PCM data from vibration effects.
 *
 * <p>This session allows an application to create one or more {@link HapticGeneratorChannelStream}
 * instances, each corresponding to a single {@link VibrationEffect} conversion.
 *
 * <p>The session must be closed via the {@link #close()} method when it is no longer needed to
 * release system resources.
 *
 * @hide
 */
@FlaggedApi(Flags.FLAG_HAPTIC_PCM_GENERATION)
@SystemApi
public final class HapticGeneratorSession implements AutoCloseable {
    private static final String TAG = "HapticGeneratorSession";

    private final IHapticGeneratorSession mSession;

    /**
     * Configuration used for starting a new {@link HapticGeneratorSession}.
     *
     * <p>This configuration includes the {@link AudioFormat} that will be applied to all PCM
     * generated by this session.
     */
    public static final class Config implements Parcelable {
        private final AudioFormat mAudioFormat;
        private final ParcelableHolder mVendorExtension;

        /**
         * Creates a new configuration for a haptic generator session.
         *
         * @param audioFormat     The audio format of the PCM data to be generated.
         *                        <p>The format must satisfy the following requirements:
         *                         <ol>
         *                        <li>Sample rate must be a positive non-zero value.</li>
         *                        <li>Must specify at least one valid channel configuration,
         *                        either via a channel mask or a channel index mask.
         *                        See {@link AudioFormat} for valid channel masks.</li>
         *                        </ol>
         * @param vendorExtension An optional parcelable for vendor-specific data. Can be null.
         * @throws IllegalArgumentException if the AudioFormat is invalid.
         */
        public Config(@NonNull AudioFormat audioFormat,
                @Nullable ParcelableHolder vendorExtension) {
            this.mAudioFormat = requireNonNull(audioFormat, "Audio format cannot be null");
            this.mVendorExtension = vendorExtension;

            validate();
        }

        private Config(Parcel in) {
            mAudioFormat = in.readTypedObject(AudioFormat.CREATOR);
            mVendorExtension = in.readTypedObject(ParcelableHolder.CREATOR);
        }

        /**
         * Returns the audio format configuration for this haptic generator session.
         */
        @NonNull
        public AudioFormat getAudioFormat() {
            return mAudioFormat;
        }

        /**
         * Returns the optional vendor-specific data, or {@code null} if not set.
         */
        @Nullable
        public ParcelableHolder getVendorExtension() {
            return mVendorExtension;
        }

        @Override
        public int describeContents() {
            return 0;
        }

        @Override
        public void writeToParcel(@NonNull Parcel dest, int flags) {
            dest.writeTypedObject(mAudioFormat, flags);
            dest.writeTypedObject(mVendorExtension, flags);
        }

        public static final @NonNull Parcelable.Creator<Config> CREATOR =
                new Parcelable.Creator<Config>() {
                    @Override
                    public Config createFromParcel(Parcel in) {
                        return new Config(in);
                    }

                    @Override
                    public Config[] newArray(int size) {
                        return new Config[size];
                    }
                };

        /**
         * Validates this configuration for the haptic generator.
         *
         * Throws IllegalArgumentException if the format is invalid.
         * @hide
         */
        public void validate() {
            Preconditions.checkArgumentPositive(mAudioFormat.getSampleRate(),
                    "Sample rate must be greater than zero.");

            int channelMask = mAudioFormat.getChannelMask();
            int indexMask = mAudioFormat.getChannelIndexMask();

            Preconditions.checkArgument((channelMask != AudioFormat.CHANNEL_INVALID) || (indexMask
                            != AudioFormat.CHANNEL_INVALID),
                    "Audio format must have a valid channel mask or index mask.");
        }
    }

    /** @hide */
    public HapticGeneratorSession(@NonNull IHapticGeneratorSession session) {
        this.mSession = session;
    }

    /**
     * Creates a new {@link HapticGeneratorChannelStream} to convert the given
     * {@link VibrationEffect} into haptic PCM data.
     *
     * <p>The effect must not be a repeating vibration. If it is, an
     * {@link IllegalArgumentException} will be thrown.
     *
     * <p>Only one conversion stream can be active at a time for a given session. Calling this
     * method will automatically close any previously opened stream from this session before
     * returning the new one.
     *
     * @param effect The {@link VibrationEffect} to be converted.
     * @return A new {@link HapticGeneratorChannelStream} to read the resulting haptic PCM data.
     * @throws IllegalArgumentException if the effect is a repeating vibration.
     */
    @NonNull
    @RequiresPermission(android.Manifest.permission.USE_VIBRATOR_HAPTIC_GENERATOR)
    public HapticGeneratorChannelStream generateHapticChannelStream(
            @NonNull VibrationEffect effect) {
        Preconditions.checkArgument(effect.getDuration() < Long.MAX_VALUE,
                "Can't generate haptic channel stream for an indefinitely repeating effect.");
        //TODO(437846004) remove this check once we support VendorEffects in the HAL.
        Preconditions.checkArgument(effect instanceof VibrationEffect.Composed,
                "Can't generate haptic channel stream for a vendor effect.");

        try {
            IHapticChannelStream stream = mSession.generateHapticChannelStream(effect);
            return new HapticGeneratorChannelStream(stream);
        } catch (RemoteException e) {
            Slog.e(TAG, "Failed to create haptic channel input stream", e);
            throw e.rethrowAsRuntimeException();
        }
    }

    /**
     * Closes this session and releases all associated system resources.
     *
     * <p>After a session has been closed, any further method calls will result in an
     * {@link IllegalStateException}. Closing a session also invalidates any open streams
     * that were created by it.
     */
    @Override
    @RequiresPermission(android.Manifest.permission.USE_VIBRATOR_HAPTIC_GENERATOR)
    public void close() {
        try {
            mSession.close();
        } catch (RemoteException e) {
            Slog.e(TAG, "Failed to close haptic generator session", e);
            throw e.rethrowAsRuntimeException();
        }
    }
}
