/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.content.pm;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;
import android.annotation.SystemApi;
import android.annotation.TestApi;
import android.os.Parcelable;

import com.android.internal.util.DataClass;

/**
 * Information about {@link android.R.styleable#AndroidManifestValidGeneralPurpose
 * &lt;valid-general-purpose&gt;} tag parsed from the manifest.
 *
 * @hide
 */
@DataClass(genConstructor = false, genParcelable = true, genEqualsHashCode = true)
@SystemApi
@FlaggedApi(android.permission.flags.Flags.FLAG_PPD_MANIFEST_ENABLED)
public final class ValidGeneralPurposeInfo implements Parcelable {
    /**
     * The name of the valid general purpose.
     */
    @NonNull
    private final String mName;

    /**
     * The maximum target SDK version that this valid general purpose can be used in. Used to
     * deprecate valid general purposes.
     */
    private final int mMaxTargetSdkVersion;

    /**
     * @param name Name of valid general purpose,
     * @param maxTargetSdkVersion Max target SDK version this purpose is valid for,
     * @hide
     */
    @TestApi
    @FlaggedApi(android.permission.flags.Flags.FLAG_PPD_MANIFEST_ENABLED)
    public ValidGeneralPurposeInfo(
            @NonNull String name,
            int maxTargetSdkVersion) {
        this.mName = name;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mName);
        this.mMaxTargetSdkVersion = maxTargetSdkVersion;
    }



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/frameworks/base/core/java/android/content/pm/ValidGeneralPurposeInfo.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    /**
     * The name of the valid general purpose.
     */
    @DataClass.Generated.Member
    public @NonNull String getName() {
        return mName;
    }

    /**
     * The maximum target SDK version that this valid general purpose can be used in. Used to
     * deprecate valid general purposes.
     */
    @DataClass.Generated.Member
    public int getMaxTargetSdkVersion() {
        return mMaxTargetSdkVersion;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(ValidGeneralPurposeInfo other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        ValidGeneralPurposeInfo that = (ValidGeneralPurposeInfo) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mName, that.mName)
                && mMaxTargetSdkVersion == that.mMaxTargetSdkVersion;
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mName);
        _hash = 31 * _hash + mMaxTargetSdkVersion;
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        dest.writeString(mName);
        dest.writeInt(mMaxTargetSdkVersion);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ ValidGeneralPurposeInfo(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        String name = in.readString();
        int maxTargetSdkVersion = in.readInt();

        this.mName = name;
        com.android.internal.util.AnnotationValidations.validate(
                NonNull.class, null, mName);
        this.mMaxTargetSdkVersion = maxTargetSdkVersion;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<ValidGeneralPurposeInfo> CREATOR
            = new Parcelable.Creator<ValidGeneralPurposeInfo>() {
        @Override
        public ValidGeneralPurposeInfo[] newArray(int size) {
            return new ValidGeneralPurposeInfo[size];
        }

        @Override
        public ValidGeneralPurposeInfo createFromParcel(@NonNull android.os.Parcel in) {
            return new ValidGeneralPurposeInfo(in);
        }
    };

    @DataClass.Generated(
            time = 1759938053722L,
            codegenVersion = "1.0.23",
            sourceFile = "frameworks/base/core/java/android/content/pm/ValidGeneralPurposeInfo.java",
            inputSignatures = "private final @android.annotation.NonNull java.lang.String mName\nprivate final  int mMaxTargetSdkVersion\nclass ValidGeneralPurposeInfo extends java.lang.Object implements [android.os.Parcelable]\n@com.android.internal.util.DataClass(genConstructor=false, genParcelable=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
