/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.provider.mediaprocessingservice;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;
import android.annotation.SystemApi;
import android.os.Build;
import android.os.Parcel;
import android.os.Parcelable;

import androidx.annotation.RequiresApi;

import com.android.providers.media.flags.Flags;

import java.util.Objects;

/**
 * Represents an embedding (floating-point vector) generated by any model
 *
 * @hide
 */
@SystemApi
@RequiresApi(Build.VERSION_CODES.TIRAMISU)
@FlaggedApi(Flags.FLAG_ENABLE_MEDIA_PROCESSING_SERVICE)
public final class EmbeddingVector implements Parcelable {
    private final float[] mValues;
    private final String mModelSignature;

    /**
     * Constructs a new {@code EmbeddingVector}.
     *
     * @param values         the array of float values representing the embedding. The contents
     *                       of the array are copied.
     * @param modelSignature a string uniquely identifying the model and version that
     *                       generated this embedding.
     */
    public EmbeddingVector(@NonNull float[] values, @NonNull String modelSignature) {
        Objects.requireNonNull(values, "values must not be null");
        Objects.requireNonNull(modelSignature, "modelSignature must not be null");

        mValues = values.clone();
        mModelSignature = modelSignature;
    }

    private EmbeddingVector(Parcel in) {
        mValues = Objects.requireNonNull(in.createFloatArray(),
                "EmbeddingVector values array must not be null");
        mModelSignature = in.readString();
    }

    /**
     * Returns the array of float values representing the embedding vector.
     *
     * @return A float array containing the embedding vector data.
     */
    @NonNull
    public float[] getValues() {
        return mValues.clone();
    }

    /**
     * Returns the unique signature string of the model used to generate this embedding.
     * <p>
     * This signature can be used to identify the specific model version and configuration, ensuring
     * that comparisons are only made between embeddings generated by compatible models.
     *
     * @return The model signature string.
     */
    @NonNull
    public String getModelSignature() {
        return mModelSignature;
    }

    @NonNull
    public static final Creator<EmbeddingVector> CREATOR = new Creator<EmbeddingVector>() {
        @Override
        public EmbeddingVector createFromParcel(Parcel in) {
            return new EmbeddingVector(in);
        }

        @Override
        public EmbeddingVector[] newArray(int size) {
            return new EmbeddingVector[size];
        }
    };

    /**
     * {@inheritDoc}
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * @param dest  The Parcel in which the object should be written.
     * @param flags Additional flags about how the object should be written.
     */
    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        Objects.requireNonNull(dest);
        dest.writeFloatArray(mValues);
        dest.writeString(mModelSignature);
    }
}
