/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.hardware.input;

import android.annotation.FlaggedApi;
import android.annotation.NonNull;
import android.annotation.SystemApi;
import android.companion.virtualdevice.flags.Flags;
import android.os.Parcel;
import android.os.Parcelable;
import android.view.InputDevice;
import android.view.MotionEvent;

import java.util.Objects;

/**
 * Configurations to specify the {@link InputDevice.ViewBehavior} for a virtual input device.
 *
 * @hide
 */
@SystemApi
@FlaggedApi(Flags.FLAG_VIRTUAL_INPUT_VIEW_BEHAVIOR)
public final class ViewBehaviorConfig implements Parcelable {

    private final int mPrimaryDirectionalMotionAxis;
    private final boolean mShouldSmoothScroll;

    private ViewBehaviorConfig(int primaryDirectionalMotionAxis,
            boolean shouldSmoothScroll) {
        mPrimaryDirectionalMotionAxis = primaryDirectionalMotionAxis;
        mShouldSmoothScroll = shouldSmoothScroll;
    }

    private ViewBehaviorConfig(Parcel in) {
        this(in.readInt(), in.readBoolean());
    }

    /** @hide */
    public ViewBehaviorConfig(@NonNull ViewBehaviorConfig other) {
        this(other.mPrimaryDirectionalMotionAxis, other.mShouldSmoothScroll);
    }

    /**
     * Returns the primary directional motion axis of the input device described as one of the
     * {@link MotionEvent} axes.
     *
     * @see InputDevice.ViewBehavior#getPrimaryDirectionalMotionAxis
     */
    @MotionEvent.Axis
    public int getPrimaryDirectionalMotionAxis() {
        return mPrimaryDirectionalMotionAxis;
    }

    /**
     * Returns whether a view should smooth scroll when scrolling due to a {@link MotionEvent}
     * generated by the input device.
     *
     * @see InputDevice.ViewBehavior#shouldSmoothScroll(int, int)
     */
    public boolean shouldSmoothScroll() {
        return mShouldSmoothScroll;
    }

    @Override
    public void writeToParcel(@NonNull Parcel dest, int flags) {
        dest.writeInt(mPrimaryDirectionalMotionAxis);
        dest.writeBoolean(mShouldSmoothScroll);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public String toString() {
        return "ViewBehaviorConfig{"
                + "mPrimaryDirectionalMotionAxis=" + mPrimaryDirectionalMotionAxis
                + ", mShouldSmoothScroll=" + mShouldSmoothScroll
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof ViewBehaviorConfig that)) {
            return false;
        }
        return mPrimaryDirectionalMotionAxis == that.mPrimaryDirectionalMotionAxis
                && mShouldSmoothScroll == that.mShouldSmoothScroll;
    }

    @Override
    public int hashCode() {
        return Objects.hash(mPrimaryDirectionalMotionAxis, mShouldSmoothScroll);
    }

    @NonNull
    public static final Creator<ViewBehaviorConfig> CREATOR = new Creator<>() {
        @Override
        public ViewBehaviorConfig createFromParcel(Parcel in) {
            return new ViewBehaviorConfig(in);
        }

        @Override
        public ViewBehaviorConfig[] newArray(int size) {
            return new ViewBehaviorConfig[size];
        }
    };

    /**
     * Builder for {@link ViewBehaviorConfig}.
     *
     * @hide
     */
    @SystemApi
    @FlaggedApi(Flags.FLAG_VIRTUAL_INPUT_VIEW_BEHAVIOR)
    public static final class Builder {
        private int mPrimaryDirectionalMotionAxis =
                InputDevice.UNSPECIFIED_PRIMARY_DIRECTIONAL_MOTION_AXIS;
        private boolean mShouldSmoothScroll = InputDevice.ViewBehavior.DEFAULT_SHOULD_SMOOTH_SCROLL;

        /**
         * Sets the primary directional motion axis of the input device described as one of the
         * {@link MotionEvent} axes.
         *
         * <p>By default, this is set to
         * {@code InputDevice.UNSPECIFIED_PRIMARY_DIRECTIONAL_MOTION_AXIS}, which indicates that
         * there is no specified primary directional motion axis.
         *
         * @return this builder, to allow for chaining of calls.
         *
         * @throws IllegalArgumentException if an invalid axis is given.
         * @see #getPrimaryDirectionalMotionAxis
         */
        @NonNull
        public Builder setPrimaryDirectionalMotionAxis(@MotionEvent.Axis int axis) {
            if (!MotionEvent.isValidAxis(axis)) {
                throw new IllegalArgumentException(
                        "Invalid primary directional motion axis: " + axis);
            }
            mPrimaryDirectionalMotionAxis = axis;
            return this;
        }

        /**
         * Sets whether a view should smooth scroll when scrolling due to a {@link MotionEvent}
         * generated by the input device.
         *
         * <p>By default, this is set to {@code false}.
         *
         * @return this builder, to allow for chaining of calls.
         *
         * @see #shouldSmoothScroll
         */
        @NonNull
        public Builder setShouldSmoothScroll(boolean shouldSmoothScroll) {
            mShouldSmoothScroll = shouldSmoothScroll;
            return this;
        }

        /**
         * Builds the {@link ViewBehaviorConfig} instance.
         */
        @NonNull
        public ViewBehaviorConfig build() {
            return new ViewBehaviorConfig(mPrimaryDirectionalMotionAxis, mShouldSmoothScroll);
        }
    }
}
